# Generated by Django 4.2.4 on 2023-10-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='https://res.cloudinary.com/smart-code-dev/image/upload/v1654989811/media/default.png', upload_to='profile_pics'),
        ),
    ]
