# Generated by Django 4.2.3 on 2023-07-28 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0002_rename_sender_message_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='DirectMessage',
        ),
    ]
