# Generated by Django 4.2.4 on 2023-08-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_rename_message_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
